name: social_spot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  #sdk: '>=3.4.3 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  retrofit: ^4.0.1
  share_plus: ^11.1.0
  webview_flutter: ^4.4.2 # For Android/iOS/Web
  webview_flutter_android: ^3.12.1
  webview_flutter_platform_interface: ^2.6.0
  webview_flutter_wkwebview: ^3.9.4
  # If you target Windows, uncomment the next line:
  # webview_windows: ^0.2.0
  freezed_annotation: ^2.3.0
  permission_handler: ^12.0.1
  open_settings_plus: ^0.4.0
  network_info_plus: ^6.1.4
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.10+1
  riverpod_annotation: ^2.3.3
  internet_connection_checker_plus: ^2.5.0
  hugeicons: ^0.0.5
  url_launcher: ^6.3.0
  gap: ^3.0.1
  carousel_slider: 5.1.1
  cached_network_image: ^3.3.1
  video_player: ^2.9.1
  wifi_scan: ^0.4.1+2
  wifi_iot: ^0.3.19+2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.9.0
  riverpod_generator: ^2.3.9
  #riverpod_lint: ^2.3.7
  retrofit_generator: ^9.2.0
  freezed: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts: 
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-Black.ttf
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf